# This workflow is used to build all the wheels and source distributions for
# the project and, on tags and releases, upload them. It is enabled on every
# commit to ensure that the wheels can be built on all platforms, but releases
# are only triggered in two situations:
#
# 1. When a tag is created, the workflow will upload the package to
#    test.pypi.org.
# 2. When a release is made, the workflow will upload the package to pypi.org.
#
# It is done this way until PyPI has draft reviews, to allow for a two-stage
# upload with a chance for manual intervention before the final publication.
name: Build and release

on:
  push:
  release:
    types: [created]

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.6', '3.7', '3.8' ]
        arch: [ 'x86', 'x64' ]
        os:
          - 'windows-latest'
          - 'macos-latest'
        include:
          - os: 'macos-latest'
            arch: 'universal2'
        exclude:
          - os: 'macos-latest'
            arch: 'x86'

    name: 'Build wheel: ${{ matrix.os }} ${{ matrix.python_version }} (${{ matrix.arch }})'
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: matrix.os == 'windows-latest'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U tox
      - name: Create tox environment
        run: tox -e build --notest
      - name: Build wheel
        env:
          CL: ${{ matrix.os == 'windows-latest' && '/WX' || '' }}
        run: |
          tox -e build -- -w
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
